class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'WORTH NETWORK',
      
      // Login Page
      'login_title': 'Email or Username',
      'login_placeholder': 'Enter your email or username',
      'password_title': 'Password',
      'password_placeholder': 'Enter your password',
      'remember_me': 'Remember me',
      'forgot_password': 'Forgot Password?',
      'login_button': 'Log In',
      'dont_have_account': "Don't have an account? ",
      'signup_button': 'Sign Up',
      'welcome_back': 'Welcome back!',
      'enter_email_error': 'Please enter your email or username',
      'enter_password_error': 'Please enter your password',
      
      // Onboarding (Welcome Page)
      'credibility_cycle': 'The Credibility Cycle',
      'credibility_cycle_desc': 'Build your real-life reputation through verified actions.',
      'step_action': 'Action',
      'step_action_desc': 'Perform a positive real-world deed.',
      'step_proof': 'Proof',
      'step_proof_desc': 'Upload images, audio, documents, or text.',
      'step_validation': 'Validation',
      'step_validation_desc': 'Get reviewed and confirmed by validators.',
      'step_worth': 'Worth',
      'step_worth_desc': 'Grow your score, unlock badges, and level up.',
      'btn_next': 'Next',
      'btn_get_started': 'Get Started',
      
      'proof_over_posts': 'Proof Over Posts',
      'proof_over_posts_desc': 'A decentralized reputation engine powered by action.',
      'val_perform_actions': 'Perform actions',
      'val_perform_actions_desc': 'Log and organize your day-to-day positive deeds, impact, and mentoring tasks.',
      'val_upload_proof': 'Upload proof',
      'val_upload_proof_desc': 'Use photos, files, or voice records. Every action supports different credibility states.',
      'val_get_validated': 'Get validated',
      'val_get_validated_desc': 'Validators verify authenticity to confirm or certify your logged action.',
      'val_build_reputation': 'Build your reputation',
      'val_build_reputation_desc': 'Enhance your score, advance levels, and earn premium badges for consistency.',
      
      // Home Page
      'no_actions_yet': 'No actions yet',
      'no_actions_desc': 'Be the first to share a real-life action.\nYour worth is built by what you do.',
      'add_first_action_btn': 'Add Your First Action',
      'pull_to_refresh': 'Pull to refresh',
      
      // Settings Page
      'settings_title': 'Settings',
      'sec_account': 'Account',
      'edit_profile_details': 'Edit Profile Details',
      'edit_profile_desc': 'Update username, bio, and profile photo',
      'sec_privacy': 'Privacy Settings',
      'private_profile': 'Private Profile',
      'private_profile_desc': 'Only validated contacts can view actions',
      'hide_reputation_score': 'Hide Reputation Score',
      'hide_reputation_desc': 'Temporarily hide total Worth Score from feed',
      'validation_invitations': 'Validation Invitations',
      'validation_invitations_desc': 'Allow users to invite you to validate deeds',
      'sec_general': 'General',
      'about_worth_concept': 'About Worth Concept',
      'about_worth_desc': 'Learn about credibility scoring engine',
      'privacy_policy': 'Privacy Policy',
      'privacy_policy_desc': 'Read our platform privacy guidelines',
      'logout_btn': 'Log Out',
      'logout_dialog_title': 'Log Out',
      'logout_dialog_desc': 'Are you sure you want to log out of Worth Network?',
      'cancel': 'Cancel',
      'dismiss': 'Dismiss',
      'about_worth_popup_title': 'About Worth Network',
      'about_worth_popup_text': 'WORTH is a social platform built on decentralized credibility.\n\nUnlike other platforms that measure engagement through passive interactions, WORTH emphasizes real-life positive deeds, verified proof, and decentralized validators to compute a confidence-score for reputation.\n\nVersion: 1.0.0 (Production Build)',

      // Sign Up Page
      'create_account': 'Create Account',
      'create_account_desc': 'Join Worth Network and start building your reputation',
      'profile_photo_optional': 'Profile Photo (Optional)',
      'change_photo': 'Change photo',
      'add_photo': 'Add photo',
      'full_name_title': 'Full Name',
      'full_name_placeholder': 'Enter your full name',
      'username_title': 'Username',
      'username_placeholder': 'Choose a unique username',
      'email_title': 'Email',
      'email_placeholder': 'Enter your email',
      'confirm_password_title': 'Confirm Password',
      'confirm_password_placeholder': 'Re-enter your password',
      'agree_terms': 'I agree to the ',
      'terms_of_service': 'Terms of Service',
      'and_text': ' and ',
      'already_have_account_signup': 'Already have an account? ',
      'account_created_success': 'Account created successfully!',
      'accept_terms_warning': 'Please accept the terms and conditions',
      'photo_size_warning': 'Profile picture size must be less than 2MB',
      
      // Profile Setup Page
      'complete_profile': 'Complete Your Profile',
      'complete_profile_desc': 'Set up your public persona on Worth Network',
      'bio_title': 'Bio',
      'bio_placeholder': 'Tell the community about yourself...',
      'continue_btn': 'Continue',
      'profile_completed_success': 'Profile completed successfully!',
      
      // Edit Profile Page
      'edit_profile': 'Edit Profile',
      'take_photo': 'Take photo',
      'choose_from_gallery': 'Choose from gallery',
      'save_changes': 'Save Changes',
      'profile_updated_success': 'Profile updated successfully!',
      
      // Profile Page & Stats
      'worth_score': 'Worth Score',
      'validated_actions': 'Validated Actions',
      'reputation_level': 'Reputation Level',
      'badges_achieved': 'Badges Achieved',
      'recent_actions': 'Recent Actions',

      // Actions & Categories
      'select_category': 'Select Category',
      'action_title': 'Action Title',
      'description_title': 'Description',
      'attach_evidence': 'Attach Evidence',
      'search_validator': 'Search validator by name...',
      'submit_action': 'Submit Action',

      // History & Notifications
      'action_history': 'Action History',
      'notifications': 'Notifications',
      'no_notifications': 'No notifications yet',

      // Navigation Tabs
      'nav_home': 'Home',
      'nav_network': 'Network',
      'nav_action': 'Action',
      'nav_profile': 'Profile',
      'profile_tab': 'Profile',

      // Validation Statuses
      'status_certified': 'Certified',
      'status_confirmed': 'Confirmed',
      'status_pending': 'Pending',
      'status_rejected': 'Rejected',
      'status_declared': 'Declared',

      // Categories
      'category_support': 'Support',
      'category_health': 'Health',
      'category_work': 'Work',
      'category_community': 'Community',
      'category_education': 'Education',
      'category_other': 'Other',

      // Actions & Feed Cards
      'delete_action_title': 'Delete Action?',
      'delete_action_desc': 'Are you sure you want to delete this post? This action cannot be undone.',
      'delete_btn': 'Delete',
      'just_now': 'just now',
      'comments_title': 'Comments',
      'add_comment_placeholder': 'Add a comment...',
      'post_btn': 'Post',
      'evidence_title': 'Evidence',
      'validator_title': 'Validator',

      // History & Profile Tabs
      'tab_my_actions': 'My Actions',
      'tab_history': 'History',
      'no_history_yet': 'No history recorded yet',
      'send_validation_request': 'Send Validation Request',
      'user_reputation': 'User Reputation',
      'clear_all': 'Clear All',

      // Network Filters & Search
      'search_users_placeholder': 'Search users...',
      'filter_all': 'All',
      'filter_near_you': 'Near You',
      'filter_top_rated': 'Top Rated',
      'no_users_found': 'No users found',
      'explore_network': 'Explore the network',
      'try_different_search': 'Try a different search term',
      'connect_with_people': 'Connect with people and build your worth',
      'clear_search': 'Clear search',

      // Profile & Stats
      'stats_actions': 'Actions',
      'stats_validated': 'Validated',
      'stats_worth': 'Worth',
      'xp_progress': 'XP Progress',
      'badges_title': 'Badges',
      'log_out': 'Log Out',
      'category_environment': 'Environment',

      // Add Action Page
      'add_action_title': 'Add Action',
      'title_label': 'Title *',
      'title_placeholder': 'e.g., Helped a friend move',
      'category_label': 'Category *',
      'date_label': 'Date *',
      'request_validation_label': 'Request Validation from Person Involved',
      'description_label': 'Description *',
      'describe_placeholder': 'Describe what you did...',
      'add_proof_title': 'Add Proof (Recommended)',
      'add_proof_desc': 'Adding proof increases your action\'s credibility score',
      'proof_photo': 'Photo',
      'proof_photo_desc': 'Take or upload a photo',
      'proof_document': 'Document',
      'proof_document_desc': 'Upload PDF, DOC, or TXT',
      'proof_audio': 'Audio',
      'proof_audio_desc': 'Record audio proof',
      'proof_text': 'Text Note',
      'proof_text_desc': 'Write a text proof',
      'validation_required_title': 'Validation Required',
      'validation_required_desc': 'After posting, send this action to the person involved for validation',
      'action_submitted_success': 'Action submitted successfully!',

      // Notifications Page
      'all_caught_up': 'All caught up!',
      'no_new_notifications': 'No new updates at the moment.',
      'inspect_request': 'Inspect Request',

      // User Detail Page
      'published_actions': 'Published Actions',
      'no_published_actions': 'No actions published yet.',

      // Validation & Action Details Page
      'action_details_title': 'Action Details',
      'validation_requested_banner': 'Validation Requested',
      'validation_requested_sub': 'You are requested to validate this action',
      'validate_btn': 'Validate',
      'requested_validator_label': 'Requested Validator',
      'like_label': 'Like',
      'likes_label': 'Likes',
      'uploaded_proof_title': 'Uploaded Proof (Credibility Evidence)',
      'validate_action_title': 'Validate Action',
      'submitted_proof_title': 'Submitted Proof / Evidence',
      'your_assessment_title': 'Your Assessment',
      'assessment_yes': 'Yes',
      'assessment_partially': 'Partially',
      'assessment_no': 'No',
      'impact_weight_title': 'Impact Weight',
      'impact_weight_desc': 'Assess the significance and confidence of this action',
      'validator_notes_title': 'Validator Notes / Feedback',
      'validator_notes_hint': 'Enter details about your validation check (optional)',
      'submitting_text': 'Submitting...',
      'retry_btn': 'Retry',
      'privacy_policy_coming_soon': 'Privacy Policy details available at worth.network',
      'delete_account_btn': 'Delete Account',
      'delete_account_dialog_title': 'Delete Account?',
      'delete_account_dialog_desc': 'Are you sure you want to delete your account? All your profile data and actions will be permanently removed. This action cannot be undone.',

      // Follow / Following System & Feed
      'btn_follow': 'Follow',
      'btn_following': 'Following',
      'btn_unfollow': 'Unfollow',
      'followers_count': 'Followers',
      'following_count': 'Following',
      'no_followers_yet': 'No followers yet',
      'no_following_yet': 'Not following anyone yet',
      'cannot_follow_self': 'You cannot follow yourself',
      'connections_title': 'Connections',
      'tab_for_you_feed': 'For You',
      'tab_following_feed': 'Following',
      'no_for_you_feed_title': 'No Actions Found',
      'no_for_you_feed_desc': 'Be the first to share a real-life action with the WORTH community.',
      'no_following_feed_title': 'No Following Actions',
      'no_following_feed_desc': 'Follow people in the Network tab to see their actions here.',
      'explore_network_btn': 'Explore Network',

      // Moderation & Safety
      'report_user': 'Report User',
      'report_action': 'Report Action',
      'report_comment': 'Report Comment',
      'block_user': 'Block User',
      'block_user_dialog_title': 'Block User?',
      'block_user_dialog_desc': 'They will no longer be able to interact with your content, and their posts will be hidden from your feed.',
      'block_user_success': 'User blocked successfully',
      'select_report_reason': 'Select a reason for reporting:',
      'reason_harassment': 'Harassment or Bullying',
      'reason_hate_speech': 'Hate Speech or Discrimination',
      'reason_inappropriate': 'Inappropriate or Offensive Content',
      'reason_spam': 'Spam or Misleading',
      'reason_false_info': 'False Information',
      'reason_other': 'Other Issue',
      'additional_details_optional': 'Additional Details (Optional):',
      'report_hint_text': 'Describe why this content breaks community guidelines...',
      'submit_report_btn': 'Submit Report',
      'report_submitted_success': 'Report submitted successfully. Thank you for keeping WORTH safe!',
      
      // Admin & Management
      'admin_console_title': 'Admin Console',
      'reports_queue': 'Reports Queue',
      'content_moderation': 'Content Moderation',
      'user_moderation': 'User Moderation',
      'hide_content': 'Hide Content',
      'remove_content': 'Remove Content',
      'restore_content': 'Restore Content',
      'suspend_user': 'Suspend User',
      'activate_user': 'Activate User',
      'reason_for_moderation': 'Reason for moderation:',
      'confirm_btn': 'Confirm',
      'access_denied': 'Access Denied',
      'admin_privileges_required': 'Admin Privileges Required',
      'admin_privileges_desc': 'Only authorized admin accounts (e.g. admin@gmail.com) can access the Moderation Console.',
      'go_back': 'Go Back',
      'worth_admin': 'WORTH ADMIN',
      'moderation_console': 'Moderation Console',
      'pending_reports': 'Pending Reports',
      'reported_content': 'Reported Content',
      'reported_users': 'Reported Users',
      'suspended_users': 'Suspended Users',
      'moderation_tools': 'Moderation Tools',
      'review_resolve_sub': 'Review & resolve',
      'word_filter': 'Word Filter',
      'prohibited_words_sub': 'Prohibited words',
      'users_list': 'Users List',
      'suspend_block_sub': 'Suspend & block',
      'audit_logs': 'Audit Logs',
      'moderation_history_sub': 'Moderation history',
      'recent_reports': 'Recent Reports',
      'view_all': 'View All',
      'no_pending_reports_clear': 'No pending reports! All clear.',
      'reported_by': 'Reported By:',
      'reported_user': 'Reported User:',
      'content_type_label': 'Type:',
      'reason_label': 'Reason:',
      'content_preview_label': 'Content Preview:',
      'user_description_label': 'User Description:',
      'close_btn': 'Close',
      'resolve_btn': 'Resolve',
      'content_hidden_success': 'Content hidden successfully',
      'report_resolved_success': 'Report resolved',

      // Admin Reports Queue
      'search_reports_hint': 'Search by user, reason, or report ID...',
      'status_all': 'All Statuses',
      'status_under_review': 'Under Review',
      'status_resolved': 'Resolved',
      'status_dismissed': 'Dismissed',
      'type_all': 'All Types',
      'type_actions': 'Actions',
      'type_comments': 'Comments',
      'type_users': 'Users',
      'no_reports_match': 'No reports match the selected filters.',
      'internal_note_title': 'Internal Moderation Note:',
      'internal_note_hint': 'Add note for moderation record...',
      'content_actions': 'Content Actions:',
      'user_actions': 'User Actions:',
      'report_status': 'Report Status:',
      'dismiss_btn': 'Dismiss',
      'mark_resolved_btn': 'Mark Resolved',
      'report_dismissed_toast': 'Report dismissed',
      'content_hidden_toast': 'Content temporarily hidden',
      'content_removed_toast': 'Content removed from public feeds',
      'user_suspended_toast': 'User account suspended',
      'user_blocked_toast': 'User blocked by admin',

      // Admin Content Moderation
      'content_moderation_title': 'Content Moderation',
      'search_content_hint': 'Search by title, author, description...',
      'filter_all_content': 'All Content',
      'filter_visible_only': 'Visible Only',
      'filter_hidden': 'Hidden',
      'filter_removed': 'Removed',
      'restore_btn': 'Restore',
      'hide_btn': 'Hide',
      'remove_btn': 'Remove',
      'no_content_found': 'No content found.',
      'reason_for_moderation_label': 'Reason for moderation:',
      'enter_reason_hint': 'Enter reason...',
      'status_changed_toast': 'Content status changed to {status}',

      // Admin User Moderation
      'user_moderation_title': 'User Moderation',
      'search_user_hint': 'Search user by name or username...',
      'filter_all_accounts': 'All Accounts',
      'filter_active': 'Active',
      'filter_suspended': 'Suspended',
      'filter_blocked': 'Blocked',
      'suspend_account_title': 'Suspend Account',
      'block_account_title': 'Block Account',
      'reactivate_account_title': 'Re-activate Account',
      'reason_status_change': 'Reason for status change:',
      'audit_log_hint': 'Enter reason for audit log...',
      'user_status_updated_toast': 'User status updated to {status}',
      'no_users_found_admin': 'No users found.',

      // Admin Word Filter
      'prohibited_word_filter': 'Prohibited Word Filter',
      'manage_abusive_words': 'Manage Abusive & Prohibited Words',
      'word_filter_desc': 'User-generated content (actions, comments, bio) will be checked against this list before publishing.',
      'enter_prohibited_word_hint': 'Enter new prohibited word...',
      'add_word_btn': '+ Add Word',
      'no_blocked_words': 'No blocked words configured.',
      'added_word_toast': 'Added to blocked word list',
      'removed_word_toast': 'Removed from blocked word list',

      // Admin Audit Logs & Detail Labels
      'moderation_audit_logs': 'Moderation Audit Logs',
      'no_audit_logs_title': 'No Audit Logs',
      'no_audit_logs_desc': 'Administrative moderation actions will be recorded here.',
      'admin_label': 'Admin:',
      'target_user_label': 'Target User:',
      'target_content_id_label': 'Target Content ID:',
      'action_label': 'Action:',
      'author_label': 'Author:',
      'user_label': 'User:',
      'default_user_name': 'User',
      'default_admin_action_reason': 'Admin action',
      'default_admin_status_reason': 'Admin status update',
      'default_hidden_report_reason': 'Temporarily hidden via admin report',
      'default_removed_report_reason': 'Removed for policy violation',
      'default_suspended_report_reason': 'Account suspended via report',
      'default_blocked_report_reason': 'Blocked by admin moderation',
      'error_adding_word': 'Error adding word:',
      'error_removing_word': 'Error removing word:',
      'action_type_hide_content': 'HIDE CONTENT',
      'action_type_remove_content': 'REMOVE CONTENT',
      'action_type_restore_content': 'RESTORE CONTENT',
      'action_type_suspend_user': 'SUSPEND USER',
      'action_type_block_user': 'BLOCK USER',
      'action_type_resolve_report': 'RESOLVE REPORT',
      'action_type_dismiss_report': 'DISMISS REPORT',

      // Edit Profile, Account Types & Roles
      'edit_profile_title': 'Edit Profile',
      'save_btn': 'Save',
      'tap_to_change_avatar': 'Tap to change profile picture',
      'full_name_label': 'Full Name',
      'full_name_required': 'Full Name is required',
      'bio_label': 'Bio',
      'bio_placeholder': 'Tell the community about your actions and goals...',
      'account_type_label': 'Account Type',
      'optional': 'Optional',
      'optional_multi_select': 'Optional (Multi-select)',
      'select_account_type_hint': 'Select type (e.g. Particular, NGO, Business)',
      'not_specified': 'Not Specified',
      'roles_domains_label': 'Roles & Domains',
      'username_label': 'Username',
      'username_helper': 'Username is unique and cannot be changed.',
      'email_label': 'Email Address',
      'email_helper': 'Email address is linked to your login account.',
      'read_only': 'Read Only',
      'image_size_exceeds_limit': 'Profile image size exceeds 10MB limit. Please choose a smaller image.',

      // Account Types
      'account_type_particular': 'Particular',
      'account_type_association': 'Association',
      'account_type_business': 'Business',
      'account_type_foundation': 'Foundation / NGO',
      'account_type_institution': 'Institution / Community',
      'account_type_public_service': 'Public Establishment / Service',
      'account_type_other': 'Other',

      // Roles & Domains
      'role_volunteer': 'Volunteer',
      'role_healthcare': 'Healthcare professional',
      'role_first_aider': 'First aider',
      'role_firefighter': 'Firefighter',
      'role_teacher': 'Teacher / Educator',
      'role_caregiver': 'Caregiver',
      'role_entrepreneur': 'Entrepreneur',
      'role_artisan': 'Artisan',
      'role_sporty': 'Sporty',
      'role_student': 'Student',
      'role_content_creator': 'Content creator',
      'role_other': 'Other',

      // Additional localization keys for full coverage
      'blocked_users_title': 'Blocked Users',
      'blocked_users_desc': 'Manage users you have blocked',
      'unblock_user_dialog_title': 'Unblock User?',
      'unblock_user_dialog_desc': 'Are you sure you want to unblock this user? They will be able to view your content and interact with you.',
      'unblock_user_btn': 'Unblock',
      'unblocked_user_success': 'User unblocked successfully',
      'no_blocked_users_title': 'No Blocked Users',
      'no_blocked_users_desc': 'Users you block will appear here.',
      'user_blocked_badge': 'Blocked',
      'safety_moderation_sec': 'Safety & Moderation',
      'failed_to_delete_account': 'Failed to delete account: ',
      'add_text_proof_title': 'Add Text Proof',
      'add_text_proof_hint': 'Write your proof here...',
      'add_btn': 'Add',
      'add_link_proof_title': 'Add Link / URL Evidence',
      'add_link_proof_desc': 'Paste a URL link (e.g. news article, tweet, video, website) as evidence:',
      'fetch_and_add_btn': 'Fetch & Add',
      'link_web_url_label': 'Link / Web URL',
      'link_web_url_desc': 'Attach a website link or online article',
      'attached_evidence_count': 'Attached Evidence',
      'record_audio_proof_title': 'Record Audio Proof',
      'recording_status': 'Recording...',
      'tap_to_start_recording': 'Tap to start recording',
      'err_image_size_limit': 'Image size exceeds 10MB limit. Please select a smaller photo.',
      'err_doc_size_limit': 'Document size exceeds 10MB limit. Please select a smaller file.',
      'err_audio_size_limit': 'Audio size exceeds 10MB limit. Please record a shorter message.',
      'err_title_required': 'Please enter a title',
      'err_title_min_length': 'Title must be at least 5 characters',
      'err_desc_required': 'Please enter a description',
      'err_desc_min_length': 'Description must be at least 10 characters',
      'search_validator_hint': 'Search validator by name...',
      'select_btn': 'Select',
      'val_submitted_success_score': 'Validation submitted successfully! Score awarded.',
      'val_submitted_rejected': 'Validation submitted. Action marked as rejected.',
      'failed_to_submit_val': 'Failed to submit validation: ',
      'audio_play_error': 'Audio play error: ',
      'terms_of_use_eula_title': 'Terms of Use / EULA',
      'save_and_continue_btn': 'Save & Continue',
      'setup_profile_title': 'Setup Profile',
      'setup_profile_desc': 'Complete your public presence on the Worth Network.',
      'choose_profile_picture': 'Choose Profile Picture',
      'enter_username_hint': 'Enter username',
      'username_required': 'Username is required',
    },
    'fr': {
      'app_title': 'RÉSEAU WORTH',
      
      // Login Page
      'login_title': "Email ou Nom d'utilisateur",
      'login_placeholder': "Entrez votre email ou nom d'utilisateur",
      'password_title': 'Mot de passe',
      'password_placeholder': 'Entrez votre mot de passe',
      'remember_me': 'Se souvenir de moi',
      'forgot_password': 'Mot de passe oublié ?',
      'login_button': 'Se connecter',
      'dont_have_account': "Vous n'avez pas de compte ? ",
      'signup_button': "S'inscrire",
      'welcome_back': 'Bon retour !',
      'enter_email_error': "Veuillez entrer votre email ou nom d'utilisateur",
      'enter_password_error': 'Veuillez entrer votre mot de passe',
      
      // Onboarding (Welcome Page)
      'credibility_cycle': 'Le Cycle de Crédibilité',
      'credibility_cycle_desc': 'Développez votre réputation dans la vie réelle grâce à des actions vérifiées.',
      'step_action': 'Action',
      'step_action_desc': 'Effectuez une bonne action concrète.',
      'step_proof': 'Preuve',
      'step_proof_desc': 'Téléchargez des images, des audios, des documents ou du texte.',
      'step_validation': 'Validation',
      'step_validation_desc': 'Faites réviser et confirmer vos actions par des meveurs.',
      'step_worth': 'Worth',
      'step_worth_desc': 'Augmentez votre score, débloquez des badges et montez de niveau.',
      'btn_next': 'Suivant',
      'btn_get_started': 'Commencer',
      
      'proof_over_posts': 'Des preuves avant des publications',
      'proof_over_posts_desc': 'Un moteur de réputation décentralisé propulsé par les actions.',
      'val_perform_actions': 'Réalisez des actions',
      'val_perform_actions_desc': 'Consignez et organisez vos bonnes actions quotidiennes.',
      'val_upload_proof': 'Téléchargez des preuves',
      'val_upload_proof_desc': 'Utilisez des photos, fichiers ou enregistrements vocaux.',
      'val_get_validated': 'Faites-vous valider',
      'val_get_validated_desc': 'Les validateurs vérifient l\'authenticité pour confirmer vos actions.',
      'val_build_reputation': 'Développez votre réputation',
      'val_build_reputation_desc': 'Améliorez votre score et débloquez des badges.',
      
      // Home Page
      'no_actions_yet': 'Aucune action pour le moment',
      'no_actions_desc': 'Soyez le premier à partager une action concrète.\nVotre valeur se construit par ce que vous faites.',
      'add_first_action_btn': 'Ajouter votre première action',
      'pull_to_refresh': 'Tirer pour rafraîchir',
      
      // Settings Page
      'settings_title': 'Paramètres',
      'sec_account': 'Compte',
      'edit_profile_details': 'Modifier les détails du profil',
      'edit_profile_desc': 'Mettre à jour le nom, la bio et la photo de profil',
      'sec_privacy': 'Paramètres de confidentialité',
      'private_profile': 'Profil privé',
      'private_profile_desc': 'Seuls les contacts validés peuvent voir les actions',
      'hide_reputation_score': 'Masquer le score de réputation',
      'hide_reputation_desc': 'Masquer temporairement le score Worth du fil',
      'validation_invitations': 'Invitations à la validation',
      'validation_invitations_desc': 'Autoriser les utilisateurs à vous inviter à valider des actions',
      'sec_general': 'Général',
      'about_worth_concept': 'À propos du concept Worth',
      'about_worth_desc': 'En savoir plus sur le moteur de score de crédibilité',
      'privacy_policy': 'Politique de confidentialité',
      'privacy_policy_desc': 'Lire nos directives de confidentialité',
      'logout_btn': 'Se déconnecter',
      'logout_dialog_title': 'Se déconnecter',
      'logout_dialog_desc': 'Êtes-vous sûr de vouloir vous déconnecter de Worth Network ?',
      'cancel': 'Annuler',
      'dismiss': 'Fermer',
      'about_worth_popup_title': 'À propos de Worth Network',
      'about_worth_popup_text': 'WORTH est une plateforme sociale basée sur la crédibilité décentralisée.\n\nVersion : 1.0.0 (Production)',

      // Sign Up Page
      'create_account': 'Créer un compte',
      'create_account_desc': 'Rejoignez Worth Network et commencez à construire votre réputation',
      'profile_photo_optional': 'Photo de profil (Optionnel)',
      'change_photo': 'Changer la photo',
      'add_photo': 'Ajouter une photo',
      'full_name_title': 'Nom complet',
      'full_name_placeholder': 'Entrez votre nom complet',
      'username_title': "Nom d'utilisateur",
      'username_placeholder': "Choisissez un nom d'utilisateur unique",
      'email_title': 'Email',
      'email_placeholder': 'Entrez votre email',
      'confirm_password_title': 'Confirmer le mot de passe',
      'confirm_password_placeholder': 'Réentrez votre mot de passe',
      'agree_terms': "J'accepte les ",
      'terms_of_service': "Conditions d'utilisation",
      'and_text': ' et la ',
      'already_have_account_signup': 'Vous avez déjà un compte ? ',
      'account_created_success': 'Compte créé avec succès !',
      'accept_terms_warning': 'Veuillez accepter les conditions d\'utilisation',
      'photo_size_warning': 'La taille de la photo doit être inférieure à 2 Mo',
      
      // Profile Setup Page
      'complete_profile': 'Complétez votre profil',
      'complete_profile_desc': 'Configurez votre profil public sur Worth Network',
      'bio_title': 'Bio',
      'bio_placeholder': 'Parlez de vous à la communauté...',
      'continue_btn': 'Continuer',
      'profile_completed_success': 'Profil complété avec succès !',
      
      // Edit Profile Page
      'edit_profile': 'Modifier le profil',
      'take_photo': 'Prendre une photo',
      'choose_from_gallery': 'Choisir depuis la galerie',
      'save_changes': 'Enregistrer les modifications',
      'profile_updated_success': 'Profil mis à jour avec succès !',
      
      // Profile Page & Stats
      'worth_score': 'Score Worth',
      'validated_actions': 'Actions validées',
      'reputation_level': 'Niveau de réputation',
      'badges_achieved': 'Badges obtenus',
      'recent_actions': 'Actions récentes',

      // Actions & Categories
      'select_category': 'Sélectionner la catégorie',
      'action_title': "Titre de l'action",
      'description_title': 'Description',
      'attach_evidence': 'Joindre une preuve',
      'search_validator': 'Rechercher un validateur...',
      'submit_action': "Soumettre l'action",

      // History & Notifications
      'action_history': "Historique des actions",
      'notifications': 'Notifications',
      'no_notifications': 'Aucune notification pour le moment',

      // Navigation Tabs
      'nav_home': 'Accueil',
      'nav_network': 'Réseau',
      'nav_action': 'Action',
      'nav_profile': 'Profil',
      'profile_tab': 'Profil',

      // Validation Statuses
      'status_certified': 'Certifié',
      'status_confirmed': 'Confirmé',
      'status_pending': 'En attente',
      'status_rejected': 'Rejeté',
      'status_declared': 'Déclaré',

      // Categories
      'category_support': 'Soutien',
      'category_health': 'Santé',
      'category_work': 'Travail',
      'category_community': 'Communauté',
      'category_education': 'Éducation',
      'category_other': 'Autre',

      // Actions & Feed Cards
      'delete_action_title': "Supprimer l'action ?",
      'delete_action_desc': "Voulez-vous vraiment supprimer cette action ? Cette action est irréversible.",
      'delete_btn': 'Supprimer',
      'just_now': 'À l\'instant',
      'comments_title': 'Commentaires',
      'add_comment_placeholder': 'Ajouter un commentaire...',
      'post_btn': 'Publier',
      'evidence_title': 'Preuve',
      'validator_title': 'Validateur',

      // History & Profile Tabs
      'tab_my_actions': 'Mes actions',
      'tab_history': 'Historique',
      'no_history_yet': 'Aucun historique enregistré',
      'send_validation_request': 'Envoyer la demande de validation',
      'user_reputation': 'Réputation de l\'utilisateur',
      'clear_all': 'Tout effacer',

      // Network Filters & Search
      'search_users_placeholder': 'Rechercher des utilisateurs...',
      'filter_all': 'Tous',
      'filter_near_you': 'Près de chez vous',
      'filter_top_rated': 'Les mieux notés',
      'no_users_found': 'Aucun utilisateur trouvé',
      'explore_network': 'Explorer le réseau',
      'try_different_search': 'Essayez un autre terme de recherche',
      'connect_with_people': 'Connectez-vous avec des personnes',
      'clear_search': 'Effacer la recherche',

      // Profile & Stats
      'stats_actions': 'Actions',
      'stats_validated': 'Validé',
      'stats_worth': 'Worth',
      'xp_progress': 'Progression XP',
      'badges_title': 'Badges',
      'log_out': 'Se déconnecter',
      'category_environment': 'Environnement',

      // Add Action Page
      'add_action_title': 'Ajouter une action',
      'title_label': 'Titre *',
      'title_placeholder': 'ex: Aidé un ami à déménager',
      'category_label': 'Catégorie *',
      'date_label': 'Date *',
      'request_validation_label': 'Demander la validation à la personne concernée',
      'description_label': 'Description *',
      'describe_placeholder': 'Décrivez ce que vous avez fait...',
      'add_proof_title': 'Ajouter une preuve (Recommandé)',
      'add_proof_desc': 'Ajouter une preuve augmente le score de crédibilité',
      'proof_photo': 'Photo',
      'proof_photo_desc': 'Prendre ou télécharger une photo',
      'proof_document': 'Document',
      'proof_document_desc': 'Télécharger un PDF, DOC ou TXT',
      'proof_audio': 'Audio',
      'proof_audio_desc': 'Enregistrer une preuve audio',
      'proof_text': 'Note texte',
      'proof_text_desc': 'Écrire une preuve texte',
      'validation_required_title': 'Validation requise',
      'validation_required_desc': 'Après la publication, envoyez cette action pour validation',
      'action_submitted_success': 'Action soumise avec succès !',

      // Notifications Page
      'all_caught_up': 'Vous êtes à jour !',
      'no_new_notifications': 'Aucune nouvelle mise à jour.',
      'inspect_request': 'Inspecter la demande',

      // User Detail Page
      'published_actions': 'Actions publiées',
      'no_published_actions': 'Aucune action publiée pour le moment.',

      // Validation & Action Details Page
      'action_details_title': "Détails de l'action",
      'validation_requested_banner': 'Validation demandée',
      'validation_requested_sub': 'Vous êtes invité à valider cette action',
      'validate_btn': 'Valider',
      'requested_validator_label': 'Validateur demandé',
      'like_label': "J'aime",
      'likes_label': "J'aime",
      'uploaded_proof_title': 'Preuve téléchargée (Preuve de crédibilité)',
      'validate_action_title': "Valider l'action",
      'submitted_proof_title': 'Preuve / Élément de preuve soumis',
      'your_assessment_title': 'Votre évaluation',
      'assessment_yes': 'Oui',
      'assessment_partially': 'Partiellement',
      'assessment_no': 'Non',
      'impact_weight_title': "Poids de l'impact",
      'impact_weight_desc': "Évaluez l'importance et la confiance de cette action",
      'validator_notes_title': 'Notes / Commentaires du validateur',
      'validator_notes_hint': 'Saisissez les détails de votre vérification (facultatif)',
      'submitting_text': 'Envoi en cours...',
      'retry_btn': 'Réessayer',
      'privacy_policy_coming_soon': 'Détails de la politique de confidentialité sur worth.network',
      'delete_account_btn': 'Supprimer le compte',
      'delete_account_dialog_title': 'Supprimer le compte ?',
      'delete_account_dialog_desc': 'Voulez-vous vraiment supprimer votre compte ? Toutes vos données de profil et vos actions seront supprimées définitivement. Cette action est irréversible.',

      // Follow / Following System & Feed
      'btn_follow': 'Suivre',
      'btn_following': 'Abonné(e)',
      'btn_unfollow': 'Se désabonner',
      'followers_count': 'Abonnés',
      'following_count': 'Abonnements',
      'no_followers_yet': 'Aucun abonné pour le moment',
      'no_following_yet': 'Aucun abonnement pour le moment',
      'cannot_follow_self': 'Vous ne pouvez pas vous suivre vous-même',
      'connections_title': 'Relations',
      'tab_for_you_feed': 'Pour vous',
      'tab_following_feed': 'Abonnements',
      'no_for_you_feed_title': 'Aucune action trouvée',
      'no_for_you_feed_desc': 'Soyez le premier à partager une action concrète avec la communauté WORTH.',
      'no_following_feed_title': 'Aucune action des abonnements',
      'no_following_feed_desc': 'Suivez des personnes dans l\'onglet Réseau pour voir leurs actions ici.',
      'explore_network_btn': 'Explorer le Réseau',

      // Moderation & Safety
      'report_user': 'Signaler l\'utilisateur',
      'report_action': 'Signaler l\'action',
      'report_comment': 'Signaler le commentaire',
      'block_user': 'Bloquer l\'utilisateur',
      'block_user_dialog_title': 'Bloquer l\'utilisateur ?',
      'block_user_dialog_desc': 'Ils ne pourront plus interagir avec votre contenu et leurs publications seront masquées de votre fil.',
      'block_user_success': 'Utilisateur bloqué avec succès',
      'select_report_reason': 'Sélectionnez un motif de signalement :',
      'reason_harassment': 'Harcèlement ou intimidation',
      'reason_hate_speech': 'Discours haineux ou discrimination',
      'reason_inappropriate': 'Contenu inapproprié ou offensant',
      'reason_spam': 'Spam ou trompeur',
      'reason_false_info': 'Fausse information',
      'reason_other': 'Autre problème',
      'additional_details_optional': 'Détails supplémentaires (Optionnel) :',
      'report_hint_text': 'Décrivez pourquoi ce contenu enfreint les règles de la communauté...',
      'submit_report_btn': 'Soumettre le signalement',
      'report_submitted_success': 'Signalement soumis avec succès. Merci d\'aider à garder WORTH en sécurité !',

      // Admin & Management
      'admin_console_title': 'Console d\'administration',
      'reports_queue': 'File des signalements',
      'content_moderation': 'Modération des contenus',
      'user_moderation': 'Modération des utilisateurs',
      'hide_content': 'Masquer le contenu',
      'remove_content': 'Supprimer le contenu',
      'restore_content': 'Rétablir le contenu',
      'suspend_user': 'Suspendre l\'utilisateur',
      'activate_user': 'Activer l\'utilisateur',
      'reason_for_moderation': 'Motif de la modération :',
      'confirm_btn': 'Confirmer',
      'access_denied': 'Accès refusé',
      'admin_privileges_required': 'Privilèges d\'administrateur requis',
      'admin_privileges_desc': 'Seuls les comptes administrateurs autorisés (ex. admin@gmail.com) peuvent accéder à la console de modération.',
      'go_back': 'Retourner',
      'worth_admin': 'ADMIN WORTH',
      'moderation_console': 'Console de modération',
      'pending_reports': 'Signalements en attente',
      'reported_content': 'Contenu signalé',
      'reported_users': 'Utilisateurs signalés',
      'suspended_users': 'Utilisateurs suspendus',
      'moderation_tools': 'Outils de modération',
      'review_resolve_sub': 'Examiner & résoudre',
      'word_filter': 'Filtre de mots',
      'prohibited_words_sub': 'Mots interdits',
      'users_list': 'Liste des utilisateurs',
      'suspend_block_sub': 'Suspendre & bloquer',
      'audit_logs': 'Journal d\'audit',
      'moderation_history_sub': 'Historique de modération',
      'recent_reports': 'Signalements récents',
      'view_all': 'Tout voir',
      'no_pending_reports_clear': 'Aucun signalement en attente ! Tout est en ordre.',
      'reported_by': 'Signalé par :',
      'reported_user': 'Utilisateur signalé :',
      'content_type_label': 'Type :',
      'reason_label': 'Motif :',
      'content_preview_label': 'Aperçu du contenu :',
      'user_description_label': 'Description de l\'utilisateur :',
      'close_btn': 'Fermer',
      'resolve_btn': 'Résoudre',
      'content_hidden_success': 'Contenu masqué avec succès',
      'report_resolved_success': 'Signalement résolu',

      // Admin Reports Queue
      'search_reports_hint': 'Rechercher par utilisateur, motif ou ID...',
      'status_all': 'Tous les statuts',
      'status_under_review': 'En cours de révision',
      'status_resolved': 'Résolu',
      'status_dismissed': 'Classé',
      'type_all': 'Tous les types',
      'type_actions': 'Actions',
      'type_comments': 'Commentaires',
      'type_users': 'Utilisateurs',
      'no_reports_match': 'Aucun signalement ne correspond aux filtres sélectionnés.',
      'internal_note_title': 'Note interne de modération :',
      'internal_note_hint': 'Ajouter une note pour le registre de modération...',
      'content_actions': 'Actions sur le contenu :',
      'user_actions': 'Actions sur l\'utilisateur :',
      'report_status': 'Statut du signalement :',
      'dismiss_btn': 'Classer',
      'mark_resolved_btn': 'Marquer comme résolu',
      'report_dismissed_toast': 'Signalement classé',
      'content_hidden_toast': 'Contenu temporairement masqué',
      'content_removed_toast': 'Contenu supprimé des fils publics',
      'user_suspended_toast': 'Compte utilisateur suspendu',
      'user_blocked_toast': 'Utilisateur bloqué par l\'administrateur',

      // Admin Content Moderation
      'content_moderation_title': 'Modération des contenus',
      'search_content_hint': 'Rechercher par titre, auteur, description...',
      'filter_all_content': 'Tout le contenu',
      'filter_visible_only': 'Visible uniquement',
      'filter_hidden': 'Masqué',
      'filter_removed': 'Supprimé',
      'restore_btn': 'Rétablir',
      'hide_btn': 'Masquer',
      'remove_btn': 'Supprimer',
      'no_content_found': 'Aucun contenu trouvé.',
      'reason_for_moderation_label': 'Motif de la modération :',
      'enter_reason_hint': 'Entrer le motif...',
      'status_changed_toast': 'Statut du contenu changé à {status}',

      // Admin User Moderation
      'user_moderation_title': 'Modération des utilisateurs',
      'search_user_hint': 'Rechercher un utilisateur par nom ou pseudo...',
      'filter_all_accounts': 'Tous les comptes',
      'filter_active': 'Actif',
      'filter_suspended': 'Suspendu',
      'filter_blocked': 'Bloqué',
      'suspend_account_title': 'Suspendre le compte',
      'block_account_title': 'Bloquer le compte',
      'reactivate_account_title': 'Réactiver le compte',
      'reason_status_change': 'Motif du changement de statut :',
      'audit_log_hint': 'Entrer le motif pour le journal d\'audit...',
      'user_status_updated_toast': 'Statut de l\'utilisateur mis à jour à {status}',
      'no_users_found_admin': 'Aucun utilisateur trouvé.',

      // Admin Word Filter
      'prohibited_word_filter': 'Filtre de mots interdits',
      'manage_abusive_words': 'Gérer les mots abusifs & interdits',
      'word_filter_desc': 'Le contenu généré par les utilisateurs (actions, commentaires, bio) sera vérifié par rapport à cette liste avant publication.',
      'enter_prohibited_word_hint': 'Entrer un nouveau mot interdit...',
      'add_word_btn': '+ Ajouter le mot',
      'no_blocked_words': 'Aucun mot interdit configuré.',
      'added_word_toast': 'Ajouté à la liste des mots interdits',
      'removed_word_toast': 'Retiré de la liste des mots interdits',

      // Admin Audit Logs & Detail Labels
      'moderation_audit_logs': 'Journal d\'audit de modération',
      'no_audit_logs_title': 'Aucun journal d\'audit',
      'no_audit_logs_desc': 'Les actions de modération administrative seront enregistrées ici.',
      'admin_label': 'Admin :',
      'target_user_label': 'Utilisateur ciblé :',
      'target_content_id_label': 'ID du contenu ciblé :',
      'action_label': 'Action :',
      'author_label': 'Auteur :',
      'user_label': 'Utilisateur :',
      'default_user_name': 'Utilisateur',
      'default_admin_action_reason': 'Action administrative',
      'default_admin_status_reason': 'Mise à jour du statut admin',
      'default_hidden_report_reason': 'Masqué temporairement via signalement admin',
      'default_removed_report_reason': 'Supprimé pour violation des règles',
      'default_suspended_report_reason': 'Compte suspendu via signalement',
      'default_blocked_report_reason': 'Bloqué par la modération admin',
      'error_adding_word': 'Erreur lors de l\'ajout du mot :',
      'error_removing_word': 'Erreur lors du retrait du mot :',
      'action_type_hide_content': 'MASQUER CONTENU',
      'action_type_remove_content': 'SUPPRIMER CONTENU',
      'action_type_restore_content': 'RÉTABLIR CONTENU',
      'action_type_suspend_user': 'SUSPENDRE UTILISATEUR',
      'action_type_block_user': 'BLOQUER UTILISATEUR',
      'action_type_resolve_report': 'RÉSOUDRE SIGNALEMENT',
      'action_type_dismiss_report': 'CLASSER SIGNALEMENT',

      // Edit Profile, Account Types & Roles
      'edit_profile_title': 'Modifier le profil',
      'save_btn': 'Enregistrer',
      'tap_to_change_avatar': 'Appuyez pour changer la photo de profil',
      'full_name_label': 'Nom complet',
      'full_name_required': 'Le nom complet est obligatoire',
      'bio_label': 'Bio',
      'bio_placeholder': 'Parlez de vos actions et objectifs à la communauté...',
      'account_type_label': 'Type de compte',
      'optional': 'Optionnel',
      'optional_multi_select': 'Optionnel (Choix multiple)',
      'select_account_type_hint': 'Sélectionnez le type (ex. Particulier, ONG, Entreprise)',
      'not_specified': 'Non spécifié',
      'roles_domains_label': 'Rôles & Domaines',
      'username_label': 'Nom d\'utilisateur',
      'username_helper': 'Le nom d\'utilisateur est unique et ne peut pas être modifié.',
      'email_label': 'Adresse email',
      'email_helper': 'L\'adresse email est liée à votre compte de connexion.',
      'read_only': 'Lecture seule',
      'image_size_exceeds_limit': 'La taille de la photo de profil dépasse 10 Mo. Veuillez choisir une image plus petite.',

      // Account Types
      'account_type_particular': 'Particulier',
      'account_type_association': 'Association',
      'account_type_business': 'Entreprise',
      'account_type_foundation': 'Fondation / ONG',
      'account_type_institution': 'Institution / Collectivité',
      'account_type_public_service': 'Établissement / Service public',
      'account_type_other': 'Autre',

      // Roles & Domains
      'role_volunteer': 'Bénévole',
      'role_healthcare': 'Professionnel de santé',
      'role_first_aider': 'Secouriste',
      'role_firefighter': 'Sapeur-pompier',
      'role_teacher': 'Enseignant / Éducateur',
      'role_caregiver': 'Aidant',
      'role_entrepreneur': 'Entrepreneur',
      'role_artisan': 'Artisan',
      'role_sporty': 'Sportif',
      'role_student': 'Étudiant',
      'role_content_creator': 'Créateur de contenu',
      'role_other': 'Autre',

      // Additional localization keys for full coverage
      'blocked_users_title': 'Utilisateurs bloqués',
      'blocked_users_desc': 'Gérer les utilisateurs que vous avez bloqués',
      'unblock_user_dialog_title': 'Débloquer l\'utilisateur ?',
      'unblock_user_dialog_desc': 'Êtes-vous sûr de vouloir débloquer cet utilisateur ? Il pourra voir votre contenu et interagir avec vous.',
      'unblock_user_btn': 'Débloquer',
      'unblocked_user_success': 'Utilisateur débloqué avec succès',
      'no_blocked_users_title': 'Aucun utilisateur bloqué',
      'no_blocked_users_desc': 'Les utilisateurs que vous bloquez apparaîtront ici.',
      'user_blocked_badge': 'Bloqué',
      'safety_moderation_sec': 'Sécurité & Modération',
      'failed_to_delete_account': 'Échec de la suppression du compte : ',
      'add_text_proof_title': 'Ajouter une preuve textuelle',
      'add_text_proof_hint': 'Écrivez votre preuve ici...',
      'add_btn': 'Ajouter',
      'add_link_proof_title': 'Ajouter un lien / URL comme preuve',
      'add_link_proof_desc': 'Collez un lien URL (ex. article de presse, tweet, vidéo, site web) comme preuve :',
      'fetch_and_add_btn': 'Récupérer & Ajouter',
      'link_web_url_label': 'Lien / URL Web',
      'link_web_url_desc': 'Joindre un lien de site web ou article en ligne',
      'attached_evidence_count': 'Preuves jointes',
      'record_audio_proof_title': 'Enregistrer une preuve vocale',
      'recording_status': 'Enregistrement en cours...',
      'tap_to_start_recording': 'Appuyez pour démarrer l\'enregistrement',
      'err_image_size_limit': 'La taille de l\'image dépasse la limite de 10 Mo. Veuillez choisir une photo plus petite.',
      'err_doc_size_limit': 'La taille du document dépasse la limite de 10 Mo. Veuillez choisir un fichier plus petit.',
      'err_audio_size_limit': 'La taille de l\'audio dépasse la limite de 10 Mo. Veuillez enregistrer un message plus court.',
      'err_title_required': 'Veuillez saisir un titre',
      'err_title_min_length': 'Le titre doit comporter au moins 5 caractères',
      'err_desc_required': 'Veuillez saisir une description',
      'err_desc_min_length': 'La description doit comporter au moins 10 caractères',
      'search_validator_hint': 'Rechercher un validateur par nom...',
      'select_btn': 'Sélectionner',
      'val_submitted_success_score': 'Validation soumise avec succès ! Score attribué.',
      'val_submitted_rejected': 'Validation soumise. Action marquée comme rejetée.',
      'failed_to_submit_val': 'Échec de la soumission de la validation : ',
      'audio_play_error': 'Erreur de lecture audio : ',
      'terms_of_use_eula_title': 'Conditions d\'utilisation / CLUF',
      'save_and_continue_btn': 'Enregistrer & Continuer',
      'setup_profile_title': 'Configurer le profil',
      'setup_profile_desc': 'Complétez votre présence publique sur le réseau Worth.',
      'choose_profile_picture': 'Choisir une photo de profil',
      'enter_username_hint': 'Entrez le nom d\'utilisateur',
      'username_required': 'Le nom d\'utilisateur est obligatoire',
    }
  };

  String translate(String key) {
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['fr']?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
