// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP7IRPieBlHk-AFHRzlWcjAWu3xq6ZVds',
    appId: '1:143684120020:web:bf94cf87c834c012b9fa41',
    messagingSenderId: '143684120020',
    projectId: 'worth-network',
    authDomain: 'worth-network.firebaseapp.com',
    databaseURL: 'https://worth-network-default-rtdb.firebaseio.com',
    storageBucket: 'worth-network.firebasestorage.app',
    measurementId: 'G-DV1KF87NH2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT8Mx2GkeewMjwgsHs40nSqY4-pIQfmrQ',
    appId: '1:143684120020:ios:b17390274997a491b9fa41',
    messagingSenderId: '143684120020',
    projectId: 'worth-network',
    databaseURL: 'https://worth-network-default-rtdb.firebaseio.com',
    storageBucket: 'worth-network.firebasestorage.app',
    iosClientId: '143684120020-teh1lorv4n8514fq5uko6ejgacii1k4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.worthNetwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP7IRPieBlHk-AFHRzlWcjAWu3xq6ZVds',
    appId: '1:143684120020:web:d89a949bddec436cb9fa41',
    messagingSenderId: '143684120020',
    projectId: 'worth-network',
    authDomain: 'worth-network.firebaseapp.com',
    databaseURL: 'https://worth-network-default-rtdb.firebaseio.com',
    storageBucket: 'worth-network.firebasestorage.app',
    measurementId: 'G-NRVPGLTGTJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT8Mx2GkeewMjwgsHs40nSqY4-pIQfmrQ',
    appId: '1:143684120020:ios:fa8da40b4b4f68b5b9fa41',
    messagingSenderId: '143684120020',
    projectId: 'worth-network',
    databaseURL: 'https://worth-network-default-rtdb.firebaseio.com',
    storageBucket: 'worth-network.firebasestorage.app',
    iosClientId: '143684120020-1387c3auskk5m76lbgo0ne0d40l5tvmg.apps.googleusercontent.com',
    iosBundleId: 'com.rm.worthnetwork',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkNNDXPWe-gOdd7551iDpAf-G3VvusZns',
    appId: '1:143684120020:android:da4d9237bf00158eb9fa41',
    messagingSenderId: '143684120020',
    projectId: 'worth-network',
    databaseURL: 'https://worth-network-default-rtdb.firebaseio.com',
    storageBucket: 'worth-network.firebasestorage.app',
  );

}